name: Discord submission notify

on: 
  pull_request:
    branches:
      - master

jobs:
  notify:
    name: Notify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@master
    - name: Discord notification (1/2)
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: 'ALT-F4 Bot'
        DISCORD_AVATAR: 'https://raw.githubusercontent.com/AlternativeFFFF/Alt-F4/master/assets/GLOBAL/img/spider.png'
      uses: Ilshidur/action-discord@master
      with:
        args: "New pull request {{ EVENT_PAYLOAD.pull_request.number }}, created by {{ EVENT_PAYLOAD.pull_request.user.login }}."
    - name: Discord notification (2/2)
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: 'ALT-F4 Bot'
        DISCORD_AVATAR: 'https://raw.githubusercontent.com/AlternativeFFFF/Alt-F4/master/assets/GLOBAL/img/spider.png'
      uses: Ilshidur/action-discord@master
      with:
        args: "{{ EVENT_PAYLOAD.pull_request.html_url }}"
