name: Automatic Release

on:
  push:
    branches:
      - release
    paths:
      - '_posts/en/*'
      - '**.md'

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Push
        uses: actions/checkout@master
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: test
        run: |
          cat $HOME/files.json
          cat $HOME/files_modified.json
          cat $HOME/files_added.json
          cat $HOME/files_removed.json
          echo '${{ steps.file_changes.outputs.files}}'
          echo '${{ steps.file_changes.outputs.files_modified}}'
          echo '${{ steps.file_changes.outputs.files_added}}'
          echo '${{ steps.file_changes.outputs.files_removed}}'
      - name: printer
        if: {{ steps.file_changes.outputs.files_added }}
        run: |
        echo 'Ladies and gentlemen, we got em. {{ EVENT_PAYLOAD.push.commits }}'
