name: Discord Submission Notify

on:
  pull_request:
    branches:
      - master
    types:
      - opened

jobs:
  labeling:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout PR
      uses: actions/checkout@master
    - name: Labeler
      uses: docker://decathlon/pull-request-labeler-action:2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CONFIG_PATH: ${{ secrets.GITHUB_WORKSPACE }}/.github/workflows_config/Discord_Submission_Notify.yml
  notify:
    needs:
    - labeling
    name: Notify
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR
      uses: actions/checkout@master
    - uses: Dreamcodeio/pr-has-label-action@master
      id: checkLabel
      with:
        label: impact:submission
    - name: Does 'pull_request' has ${{ steps.checkLabel.outputs.checkedLabel }} label?
      run: echo "${{ steps.checkLabel.outputs.hasLabel }}"
    - name: Discord notification (1/2)
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_SUBMISSION }}
        DISCORD_USERNAME: 'ALT-F4 Bot'
        DISCORD_AVATAR: 'https://raw.githubusercontent.com/AlternativeFFFF/Alt-F4/master/assets/GLOBAL/img/spider.png'
      uses: Ilshidur/action-discord@0.2.0
      with:
        args: "New pull request {{ EVENT_PAYLOAD.pull_request.number }}, created by {{ EVENT_PAYLOAD.pull_request.user.login }}."
    - name: Discord notification (2/2)
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_SUBMISSION }}
        DISCORD_USERNAME: 'ALT-F4 Bot'
        DISCORD_AVATAR: 'https://raw.githubusercontent.com/AlternativeFFFF/Alt-F4/master/assets/GLOBAL/img/spider.png'
      uses: Ilshidur/action-discord@0.2.0
      with:
        args: "{{ EVENT_PAYLOAD.pull_request.html_url }}"
