name: Github PR labeler

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - edited

jobs:
  labeling:
    name: PR labeling
    if: github.repository == 'AlternativeFFFF/Alt-F4'
    runs-on: ubuntu-18.04
    steps:

    - name: Checkout PR
      uses: actions/checkout@master

    - name: Labeler
      uses: docker://decathlon/pull-request-labeler-action:2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.ALT_F4_BOT_PAT }}
        CONFIG_PATH: ${{ secrets.GITHUB_WORKSPACE }}/.github/workflows_config/Github_PR_Labeler.yml
