name: PR Review Notify
on: pull_request_review
jobs:
  notify:
    name: Notify
    #if: github.repository == 'AlternativeFFFF/Alt-F4'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release
        uses: actions/checkout@master
      - id: checkLabel	
        uses: Dreamcodeio/pr-has-label-action@master	
        with:	
          label: impact:submission	
      - name: Discord notification	
        if: steps.checkLabel.outputs.hasLabel
        env:
          DISCORD_WEBHOOK: '${{ secrets.DISCORD_WEBHOOK_PR_NOTIFY }}'
          DISCORD_USERNAME: ALT-F4 Bot
          DISCORD_AVATAR: 'https://raw.githubusercontent.com/AlternativeFFFF/Alt-F4/master/assets/GLOBAL/img/spider.png'
        uses: Ilshidur/action-discord@0.2.0
        with:
          args: "New review on: *{{ EVENT_PAYLOAD.review.pull_request.title }}* by: *{{ EVENT_PAYLOAD.review.user.login }}*\n`{{ EVENT_PAYLOAD.review.body }}`\n{{ EVENT_PAYLOAD.review.html_url }}"